on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.19.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          curl -s https://api.github.com/repos/shellops/shellops-panel/releases/latest | grep "panel.*zip" | cut -d : -f 2,3 | tr -d \" | wget -qi -
      - run: mv panel.zip public
      - run: cd public && unzip panel.zip
      - run: mv public/out/* public
      - run: rm public/panel.zip && rm -r out
      - run: npm install --prefer-offline --no-audit --no-progress
      - run: npm run make
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        run: DEB_FILE=$(ls out/make/deb/x64)
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: out/make/deb/x64/${{ENV.DEB_FILE}}
          asset_name: ${{ENV.DEB_FILE}}
          asset_content_type: application/vnd.debian.binary-package
